// <auto-generated />
using System;
using JobTracker.Applications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobTracker.Applications.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationsDbContext))]
    [Migration("20260912233922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobTracker.Applications.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AppliedDate")
                        .HasColumnType("date")
                        .HasColumnName("applied_date");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job_applications");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("JobTracker.Applications.Domain.Entities.JobApplication", b =>
                {
                    b.OwnsOne("JobTracker.Applications.Domain.ValueObjects.SalaryRange", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("salary_currency");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("salary_max");

                            b1.Property<decimal>("Min")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("salary_min");

                            b1.HasKey("JobApplicationId");

                            b1.ToTable("job_applications");

                            b1.WithOwner()
                                .HasForeignKey("JobApplicationId")
                                .HasConstraintName("fk_job_applications_job_applications_id");
                        });

                    b.Navigation("Salary");
                });
#pragma warning restore 612, 618
        }
    }
}
