<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fe842e41-f2dc-4f23-9884-582499fc3a7f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobTracker.Users.Application\JobTracker.Users.Application.csproj" />
    <ProjectReference Include="..\JobTracker.Users.Infrastructure\JobTracker.Users.Infrastructure.csproj" />
  </ItemGroup>

</Project>
